# Generated by Django 4.1.4 on 2023-02-07 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='media', verbose_name='Image (Optional)'),
        ),
    ]
