# Generated by Django 4.1.4 on 2023-01-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_listing_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='genre',
        ),
        migrations.AddField(
            model_name='listing',
            name='genres',
            field=models.ManyToManyField(default=None, to='auctions.genre', verbose_name='Genre(s)'),
        ),
    ]
