# Generated by Django 4.1.4 on 2023-01-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_remove_listing_genre_listing_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='genres',
            field=models.ManyToManyField(to='auctions.genre', verbose_name='Genre(s)'),
        ),
    ]
