# Generated by Django 4.1.4 on 2023-01-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_alter_listing_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watch',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.listing'),
        ),
    ]
