# Generated by Django 4.1.4 on 2023-01-17 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_remove_user_watch_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watchlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
